const currencys = [
  {
    value: "KM",
    label: "Bosnia and Herzegovina konvertibilna marka",
  },
  { value: "Bds$", label: "Barbadian dollar" },
  { value: "\u09f3", label: "Bangladeshi taka" },
  { value: "BGN", label: "Bulgarian lev" },
  { value: ".\u062f.\u0628", label: "Bahraini dinar" },
  { value: "FBu", label: "Burundi franc" },
  { value: "BD$", label: "Bermudian dollar" },
  { value: "B$", label: "Brunei dollar" },
  { value: "Bs.", label: "Bolivian boliviano" },
  { value: "R$", label: "Brazilian real" },
  { value: "B$", label: "Bahamian dollar" },
  { value: "Nu.", label: "Bhutanese ngultrum" },
  { value: "P", label: "Botswana pula" },
  { value: "Br", label: "Belarusian ruble" },
  { value: "BZ$", label: "Belize dollar" },
  { value: "$", label: "Canadian dollar" },
  { value: "F", label: "Congolese franc" },
  { value: "Fr.", label: "Swiss franc" },
  { value: "$", label: "Chilean peso" },
  { value: "\u00a5", label: "Chinese/Yuan renminbi" },
  { value: "Col$", label: "Colombian peso" },
  { value: "\u20a1", label: "Costa Rican colon" },
  { value: "$", label: "Cuban peso" },
  { value: "Esc", label: "Cape Verdean escudo" },
  { value: "K\u010d", label: "Czech koruna" },
  { value: "Fdj", label: "Djiboutian franc" },
  { value: "Kr", label: "Danish krone" },
  { value: "RD$", label: "Dominican peso" },
  { value: "\u062f.\u062c", label: "Algerian dinar" },
  { value: "KR", label: "Estonian kroon" },
  { value: "\u00a3", label: "Egyptian pound" },
  { value: "Nfa", label: "Eritrean nakfa" },
  { value: "Br", label: "Ethiopian birr" },
  { value: "\u20ac", label: "European Euro" },
  { value: "FJ$", label: "Fijian dollar" },
  { value: "\u00a3", label: "Falkland Islands pound" },
  { value: "\u00a3", label: "British pound" },
  { value: "GEL", label: "Georgian lari" },
  { value: "GH\u20b5", label: "Ghanaian cedi" },
  { value: "\u00a3", label: "Gibraltar pound" },
  { value: "D", label: "Gambian dalasi" },
  { value: "FG", label: "Guinean franc" },
  { value: "CFA", label: "Central African CFA franc" },
  { value: "Q", label: "Guatemalan quetzal" },
  { value: "GY$", label: "Guyanese dollar" },
  { value: "HK$", label: "Hong Kong dollar" },
  { value: "L", label: "Honduran lempira" },
  { value: "kn", label: "Croatian kuna" },
  { value: "G", label: "Haitian gourde" },
  { value: "Ft", label: "Hungarian forint" },
  { value: "Rp", label: "Indonesian rupiah" },
  { value: "\u20aa", label: "Israeli new sheqel" },
  { value: "\u20B9", label: "Indian rupee" },
  { value: "\u062f.\u0639", label: "Iraqi dinar" },
  { value: "IRR", label: "Iranian rial" },
  { value: "kr", label: "Icelandic kr\u00f3na" },
  { value: "J$", label: "Jamaican dollar" },
  { value: "JOD", label: "Jordanian dinar" },
  { value: "\u00a5", label: "Japanese yen" },
  { value: "KSh", label: "Kenyan shilling" },
  { value: "\u0441\u043e\u043c", label: "Kyrgyzstani som" },
  { value: "\u17db", label: "Cambodian riel" },
  { value: "KMF", label: "Comorian franc" },
  { value: "W", label: "North Korean won" },
  { value: "W", label: "South Korean won" },
  { value: "KWD", label: "Kuwaiti dinar" },
  { value: "KY$", label: "Cayman Islands dollar" },
  { value: "T", label: "Kazakhstani tenge" },
  { value: "KN", label: "Lao kip" },
  { value: "\u00a3", label: "Lebanese lira" },
  { value: "Rs", label: "Sri Lankan rupee" },
  { value: "L$", label: "Liberian dollar" },
  { value: "M", label: "Lesotho loti" },
  { value: "Lt", label: "Lithuanian litas" },
  { value: "Ls", label: "Latvian lats" },
  { value: "LD", label: "Libyan dinar" },
  { value: "MAD", label: "Moroccan dirham" },
  { value: "MDL", label: "Moldovan leu" },
  { value: "FMG", label: "Malagasy ariary" },
  { value: "MKD", label: "Macedonian denar" },
  { value: "K", label: "Myanma kyat" },
  { value: "\u20ae", label: "Mongolian tugrik" },
  { value: "P", label: "Macanese pataca" },
  { value: "UM", label: "Mauritanian ouguiya" },
  { value: "Rs", label: "Mauritian rupee" },
  { value: "Rf", label: "Maldivian rufiyaa" },
  { value: "MK", label: "Malawian kwacha" },
  { value: "$", label: "Mexican peso" },
  { value: "RM", label: "Malaysian ringgit" },
  { value: "MTn", label: "Mozambican metical" },
  { value: "N$", label: "Namibian dollar" },
  { value: "\u20a6", label: "Nigerian naira" },
  { value: "C$", label: "Nicaraguan c\u00f3rdoba" },
  { value: "kr", label: "Norwegian krone" },
  { value: "NRs", label: "Nepalese rupee" },
  { value: "NZ$", label: "New Zealand dollar" },
  { value: "OMR", label: "Omani rial" },
  { value: "B./", label: "Panamanian balboa" },
  { value: "S/.", label: "Peruvian nuevo sol" },
  { value: "K", label: "Papua New Guinean kina" },
  { value: "\u20b1", label: "Philippine peso" },
  { value: "Rs.", label: "Pakistani rupee" },
  { value: "z\u0142", label: "Polish zloty" },
  { value: "\u20b2", label: "Paraguayan guarani" },
  { value: "QR", label: "Qatari riyal" },
  { value: "L", label: "Romanian leu" },
  { value: "din.", label: "Serbian dinar" },
  { value: "R", label: "Russian ruble" },
  { value: "SR", label: "Saudi riyal" },
  { value: "SI$", label: "Solomon Islands dollar" },
  { value: "SR", label: "Seychellois rupee" },
  { value: "SDG", label: "Sudanese pound" },
  { value: "kr", label: "Swedish krona" },
  { value: "S$", label: "Singapore dollar" },
  { value: "\u00a3", label: "Saint Helena pound" },
  { value: "Le", label: "Sierra Leonean leone" },
  { value: "Sh.", label: "Somali shilling" },
  { value: "$", label: "Surinamese dollar" },
  { value: "LS", label: "Syrian pound" },
  { value: "E", label: "Swazi lilangeni" },
  { value: "\u0e3f", label: "Thai baht" },
  { value: "TJS", label: "Tajikistani somoni" },
  { value: "m", label: "Turkmen manat" },
  { value: "DT", label: "Tunisian dinar" },
  { value: "TRY", label: "Turkish new lira" },
  { value: "TT$", label: "Trinidad and Tobago dollar" },
  { value: "NT$", label: "New Taiwan dollar" },
  { value: "TZS", label: "Tanzanian shilling" },
  { value: "UAH", label: "Ukrainian hryvnia" },
  { value: "USh", label: "Ugandan shilling" },
  { value: "US$", label: "United States dollar" },
  { value: "$U", label: "Uruguayan peso" },
  { value: "UZS", label: "Uzbekistani som" },
  { value: "Bs", label: "Venezuelan bolivar" },
  { value: "\u20ab", label: "Vietnamese dong" },
  { value: "VT", label: "Vanuatu vatu" },
  { value: "WS$", label: "Samoan tala" },
  { value: "CFA", label: "Central African CFA franc" },
  { value: "EC$", label: "East Caribbean dollar" },
  { value: "SDR", label: "Special Drawing Rights" },
  { value: "CFA", label: "West African CFA franc" },
  { value: "F", label: "CFP franc" },
  { value: "YER", label: "Yemeni rial" },
  { value: "R", label: "South African rand" },
  { value: "ZK", label: "Zambian kwacha" },
  { value: "Z$", label: "Zimbabwean dollar" },
];

export default currencys;
