const data = [
  {
    id: "1",
    image: require("../assets/images/one.png"),
    name: "2 Bedroom Flat",
    amount: "150,000",
    location: "24 Collins way ibeju lekki lagos",
    bed: "2",
    bath: "2",
    sqrt: "3200",
    time: "November 20, 2022",
  },
  {
    id: "2",
    image: require("../assets/images/two.png"),
    name: "2 Bedroom Flat",
    amount: "150,000",
    location: "24 Collins way ibeju lekki lagos",
    bed: "2",
    bath: "2",
    sqrt: "3200",
    time: "November 20, 2022",
  },
  {
    id: "3",
    image: require("../assets/images/three.png"),
    name: "2 Bedroom Flat",
    amount: "150,000",
    location: "24 Collins way ibeju lekki lagos",
    bed: "2",
    bath: "2",
    sqrt: "3200",
    time: "November 20, 2022",
  },
  {
    id: "4",
    image: require("../assets/images/one.png"),
    name: "2 Bedroom Flat",
    amount: "150,000",
    location: "24 Collins way ibeju lekki lagos",
    bed: "2",
    bath: "2",
    sqrt: "3200",
    time: "November 20, 2022",
  },
  {
    id: "5",
    image: require("../assets/images/two.png"),
    name: "2 Bedroom Flat",
    amount: "150,000",
    location: "24 Collins way ibeju lekki lagos",
    bed: "2",
    bath: "2",
    sqrt: "3200",
    time: "November 20, 2022",
  },
];

export default data;
