export const GLOBALTYPES = {
  AUTH: "AUTH",
  ALERT: "ALERT",
  TOKEN: "TOKEN",
  ACTIVATION_TOKEN: "ACTIVATION_TOKEN",
  USER: "USER",
  IDENTITY_NAME: "IDENTITY_NAME",
  IDENTITY_SELFIE: "IDENTITY_SELFIE",
  IDENTITY_DOCUMENT: "IDENTITY_DOCUMENT",
  DOCUMENT_TYPE: "DOCUMENT_TYPE",
  USER_PROFILE: "USER_PROFILE",
  IDENTITY_MOBILE: "IDENTITY_MOBILE",
};
